### ISSUE TITLE
Migrate from using AuthFile to using Auth

### ISSUE THREAD

**Issue by stakach** [PlaceOS/wallet_api#6]
https://github.com/PlaceOS/google#googleauth

**Comment by jeremyw24** [comment]
@dukeraphaelng can I please get an update on this issue, close if no longer relevant.

**Comment by dukenguyenxyz** [comment]
Ill discuss this on tomorrows stand up

**Comment by dukenguyenxyz** [comment]
Just to reconfirm, you want me to migrate from using authfile (i.e. `client_auth.json`) to using ENV for Google Passes.

For Apple Passes, currently they use .pem files, and you want me to migrate them to using ENV as well?

@stakach

**Comment by stakach** [comment]
yep we want it all in the ENV versus loading files
for PEMS they should be base64 encoded so in the app they need to be decoded like:
https://github.com/PlaceOS/models/blob/317cf202a3573608f8527686e93348aa583b6fe3/src/placeos-models/base/jwt.cr#L14
