### ISSUE TITLE
Rename repo `wallet_api` -> `wallet`

### ISSUE THREAD

**Issue by kimburgess** [PlaceOS/wallet_api#8]
To keep naming consistency across other platform components, it would be good to rename this repo to `wallet`, or `wallet-api`.

This change can be made on GitHub and a redirect will be put in place, however this should be treated as temporary to aid in transitioning. Other points where this will need changing:

- [ ] update name in `shard.yml`
- [ ] update references in components that use this lib

**Comment by dukenguyenxyz** [comment]
Resolved with https://github.com/PlaceOS/wallet/commit/3a89363fe75cb4bb20d2b3afac5db7918b7d6ca8
